keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: certificacionIAS
  resource: backend
  credentials:
    secret: 4f93d1b7-489a-4ec5-b8dc-ce71276ed2ce

database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: orders