keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: orders
  resource: backend
  credentials:
    secret: abeea4aa-cfc7-49e5-adf4-beffc8dc4a79

database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: orders