CREATE TABLE PRODUCTS(
    productId BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    basePrice DECIMAL NOT NULL,
    taxRate VARCHAR NOT NULL,
    productStatus VARCHAR NOT NULL,
    inventoryQuantity INTEGER NOT NULL
);

CREATE TABLE IMAGENES(
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR NOT NULL,
    productid INTEGER NOT NULL,
    FOREIGN KEY (productid) REFERENCES PRODUCTS(productId)
);

CREATE TABLE LISTORDERS(
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    cliente VARCHAR NOT NULL,
    descuento DECIMAL NOT NULL,
    total DECIMAL NOT NULL,
    estado VARCHAR NOT NULL
);

CREATE TABLE LIST_PRODUCTS(
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    productid INTEGER NOT NULL,
    FOREIGN KEY (productid) REFERENCES PRODUCTS(productId),
    orderid INTEGER NOT NULL,
    FOREIGN KEY (orderid) REFERENCES LISTORDERS(id),
    cantidadProduct INTEGER NOT NULL
);